"""empty message

Revision ID: dd0662c10f85
Revises: a274355c4060
Create Date: 2020-07-07 19:25:20.572717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0662c10f85'
down_revision = 'a274355c4060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('artist', sa.Column('seeking_venue_description', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'seeking_venue_description')
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
